org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
android.builder.sdkDownload=false

# Fix Windows cross-drive (C: vs D:) Kotlin incremental cache crash
kotlin.incremental=false
kotlin.incremental.java=false
kotlin.incremental.js=false
kotlin.incremental.useClasspathSnapshot=false
